export interface OpenPosition {
  stat: string
  uid: string
  actid: string
  exch: string
  tsym: string
  s_prdt_ali: string
  prd: string
  token: string
  dname: string
  frzqty: string
  pp: string
  ls: string
  ti: string
  mult: string
  prcftr: string
  daybuyqty: string
  daysellqty: string
  daybuyamt: string
  daybuyavgprc: string
  daysellamt: string
  daysellavgprc: string
  cfbuyqty: string
  cfsellqty: string
  openbuyqty: string
  opensellqty: string
  openbuyamt: string
  openbuyavgprc: string
  opensellamt: string
  opensellavgprc: string
  dayavgprc: string
  netqty: string
  netavgprc: string
  upldprc: string
  netupldprc: string
  lp: string
  urmtom: string
  bep: string
  totbuyamt: string
  totsellamt: string
  totbuyavgprc: string
  rpnl: string
}
